var annotated =
[
    [ "BWAPI::AIModule", "class_b_w_a_p_i_1_1_a_i_module.html", "class_b_w_a_p_i_1_1_a_i_module" ],
    [ "BWAPI::BestFilter< _PARAM >", "class_b_w_a_p_i_1_1_best_filter.html", "class_b_w_a_p_i_1_1_best_filter" ],
    [ "BWAPI::BulletInterface", "class_b_w_a_p_i_1_1_bullet_interface.html", "class_b_w_a_p_i_1_1_bullet_interface" ],
    [ "BWAPI::Bulletset", "class_b_w_a_p_i_1_1_bulletset.html", "class_b_w_a_p_i_1_1_bulletset" ],
    [ "BWAPI::BulletType", "class_b_w_a_p_i_1_1_bullet_type.html", "class_b_w_a_p_i_1_1_bullet_type" ],
    [ "BWAPI::Color", "class_b_w_a_p_i_1_1_color.html", "class_b_w_a_p_i_1_1_color" ],
    [ "BWAPI::CompareFilter< PType, RType, Container >", "class_b_w_a_p_i_1_1_compare_filter.html", "class_b_w_a_p_i_1_1_compare_filter" ],
    [ "BWAPI::ConstVectorset< T >", "class_b_w_a_p_i_1_1_const_vectorset.html", "class_b_w_a_p_i_1_1_const_vectorset" ],
    [ "BWAPI::DamageType", "class_b_w_a_p_i_1_1_damage_type.html", "class_b_w_a_p_i_1_1_damage_type" ],
    [ "BWAPI::Error", "class_b_w_a_p_i_1_1_error.html", "class_b_w_a_p_i_1_1_error" ],
    [ "BWAPI::Event", "class_b_w_a_p_i_1_1_event.html", "class_b_w_a_p_i_1_1_event" ],
    [ "BWAPI::ExplosionType", "class_b_w_a_p_i_1_1_explosion_type.html", "class_b_w_a_p_i_1_1_explosion_type" ],
    [ "BWAPI::ForceInterface", "class_b_w_a_p_i_1_1_force_interface.html", "class_b_w_a_p_i_1_1_force_interface" ],
    [ "BWAPI::Forceset", "class_b_w_a_p_i_1_1_forceset.html", "class_b_w_a_p_i_1_1_forceset" ],
    [ "BWAPI::Game", "class_b_w_a_p_i_1_1_game.html", "class_b_w_a_p_i_1_1_game" ],
    [ "BWAPI::GameType", "class_b_w_a_p_i_1_1_game_type.html", "class_b_w_a_p_i_1_1_game_type" ],
    [ "BWAPI::GameWrapper", "class_b_w_a_p_i_1_1_game_wrapper.html", "class_b_w_a_p_i_1_1_game_wrapper" ],
    [ "BWAPI::Interface< T >", "class_b_w_a_p_i_1_1_interface.html", "class_b_w_a_p_i_1_1_interface" ],
    [ "BWAPI::InterfaceEvent< T >", "class_b_w_a_p_i_1_1_interface_event.html", "class_b_w_a_p_i_1_1_interface_event" ],
    [ "BWAPI::Order", "class_b_w_a_p_i_1_1_order.html", "class_b_w_a_p_i_1_1_order" ],
    [ "BWAPI::PlayerInterface", "class_b_w_a_p_i_1_1_player_interface.html", "class_b_w_a_p_i_1_1_player_interface" ],
    [ "BWAPI::Playerset", "class_b_w_a_p_i_1_1_playerset.html", "class_b_w_a_p_i_1_1_playerset" ],
    [ "BWAPI::PlayerType", "class_b_w_a_p_i_1_1_player_type.html", "class_b_w_a_p_i_1_1_player_type" ],
    [ "BWAPI::Point< _T, __Scale >", "class_b_w_a_p_i_1_1_point.html", "class_b_w_a_p_i_1_1_point" ],
    [ "BWAPI::Point< _T, 0 >", "class_b_w_a_p_i_1_1_point_3_01___t_00_010_01_4.html", null ],
    [ "BWAPI::Point< bool, __Scale >", "class_b_w_a_p_i_1_1_point_3_01bool_00_01_____scale_01_4.html", null ],
    [ "BWAPI::Point< char, __Scale >", "class_b_w_a_p_i_1_1_point_3_01char_00_01_____scale_01_4.html", null ],
    [ "BWAPI::Point< unsigned char, __Scale >", "class_b_w_a_p_i_1_1_point_3_01unsigned_01char_00_01_____scale_01_4.html", null ],
    [ "BWAPI::PositionOrUnit", "class_b_w_a_p_i_1_1_position_or_unit.html", "class_b_w_a_p_i_1_1_position_or_unit" ],
    [ "BWAPI::Race", "class_b_w_a_p_i_1_1_race.html", "class_b_w_a_p_i_1_1_race" ],
    [ "BWAPI::RegionInterface", "class_b_w_a_p_i_1_1_region_interface.html", "class_b_w_a_p_i_1_1_region_interface" ],
    [ "BWAPI::Regionset", "class_b_w_a_p_i_1_1_regionset.html", "class_b_w_a_p_i_1_1_regionset" ],
    [ "BWAPI::TechType", "class_b_w_a_p_i_1_1_tech_type.html", "class_b_w_a_p_i_1_1_tech_type" ],
    [ "BWAPI::TournamentModule", "class_b_w_a_p_i_1_1_tournament_module.html", "class_b_w_a_p_i_1_1_tournament_module" ],
    [ "BWAPI::Type< T, UnknownId >", "class_b_w_a_p_i_1_1_type.html", "class_b_w_a_p_i_1_1_type" ],
    [ "BWAPI::Typeset< T >", "class_b_w_a_p_i_1_1_typeset.html", "class_b_w_a_p_i_1_1_typeset" ],
    [ "BWAPI::UnaryFilter< PType, Container >", "class_b_w_a_p_i_1_1_unary_filter.html", "class_b_w_a_p_i_1_1_unary_filter" ],
    [ "BWAPI::UnitCommand", "class_b_w_a_p_i_1_1_unit_command.html", "class_b_w_a_p_i_1_1_unit_command" ],
    [ "BWAPI::UnitCommandType", "class_b_w_a_p_i_1_1_unit_command_type.html", "class_b_w_a_p_i_1_1_unit_command_type" ],
    [ "BWAPI::UnitInterface", "class_b_w_a_p_i_1_1_unit_interface.html", "class_b_w_a_p_i_1_1_unit_interface" ],
    [ "BWAPI::Unitset", "class_b_w_a_p_i_1_1_unitset.html", "class_b_w_a_p_i_1_1_unitset" ],
    [ "BWAPI::UnitSizeType", "class_b_w_a_p_i_1_1_unit_size_type.html", "class_b_w_a_p_i_1_1_unit_size_type" ],
    [ "BWAPI::UnitType", "class_b_w_a_p_i_1_1_unit_type.html", "class_b_w_a_p_i_1_1_unit_type" ],
    [ "BWAPI::UpgradeType", "class_b_w_a_p_i_1_1_upgrade_type.html", "class_b_w_a_p_i_1_1_upgrade_type" ],
    [ "BWAPI::Vectorset< _T >", "class_b_w_a_p_i_1_1_vectorset.html", "class_b_w_a_p_i_1_1_vectorset" ],
    [ "BWAPI::VSetIterator< T >", "class_b_w_a_p_i_1_1_v_set_iterator.html", "class_b_w_a_p_i_1_1_v_set_iterator" ],
    [ "BWAPI::WeaponType", "class_b_w_a_p_i_1_1_weapon_type.html", "class_b_w_a_p_i_1_1_weapon_type" ]
];