BWAPI: BWAPI::Vectorset< _T > Class Template Reference
BWAPI::Vectorset< _T > Class Template Reference
The Vectorset is a class template designed specifically for trivial classes or PODs and performance.
#include <Vectorset.h>
Public Types
typedef ConstVectorset< _T >
::iterator iterator
The iterator is used to traverse the elements in the set.
Public Member Functions
Vectorset (size_t initialSize=16)
This is the default constructor.
Vectorset (const Vectorset< _T > &other)
This is the copy constructor.
Vectorset (const ConstVectorset< _T > &other)
Vectorset (Vectorset< _T > &&other)
This is the move constructor.
Vectorset (const _T *pArray, size_t arrSize)
This constructor uses an existing array of objects and copies them into the vector.
void clear ()
Clears the Vectorset, removing all elements.
void erase (const _T &val)
Erases all values found in the Vectorset.
iterator erase (iterator iter)
Erases the value at an iterator for this Vectorset.
iterator erase (iterator first, iterator last)
Erases the values within a range of iterators for this Vectorset.
template<typename Func >
void erase_if (const Func &pred)
Works similar to the STL algorithm remove_if.
void insert (const _T &val)
Inserts a new value into the Vectorset only if it does not already exist.
void insert (const iterator &val)
void insert (const ConstVectorset< _T > &other)
Inserts all elements of another vector only if each element does not already exsist.
size_t max_size () const
Retrieves the current capacity of the Vectorset.
Vectorset & operator+= (const ConstVectorset< _T > &other)
Vectorset< _T > & operator= (const Vectorset< _T > &other)
This is the copy assignment operator.
Vectorset< _T > & operator= (const ConstVectorset< _T > &other)
Vectorset & operator= (Vectorset< _T > &&other)
This is the move assignment operator.
Vectorset & operator|= (const ConstVectorset< _T > &other)
void pop_back ()
void pop_front ()
void push_back (const _T val)
Pushes a value to the back of the Vectorset, expanding it if necessary.
void push_back (const iterator &val)
void push_back (const ConstVectorset< _T > &other)
Pushes all values of another Vectorset to the back of this one, expanding it to contain exactly the number of elements in both Vectorsets if necessary.
void push_front (const _T val)
Pushes a value to the front of the Vectorset, expanding it if necessary.
void push_front (const iterator &val)
void remove (const _T &val)
Removes all values found in the Vectorset.
void remove (const iterator &iter)
Erases the value at an iterator for this Vectorset.
template<typename Func >
void remove_if (const Func &pred)
Works similar to the STL algorithm remove_if.
Protected Member Functions
bool expand (size_t additionalElements=1)
Expands the container if it currently does not have the capacity for the number of additional elements.
Protected Attributes
_T * pEndAlloc
Detailed Description
template<typename _T>
class BWAPI::Vectorset< _T >
The Vectorset is a class template designed specifically for trivial classes or PODs and performance.
It mimics the usage of various stl containers (specifically the Vector and Set) in order to replace them. The Vectorset is designed for BWAPI usage and is recommended, especially if stl containers are causing a bottleneck in your bot's code.
Warning:
The Vectorset should only be used with objects that have a trivial destructor and trivial copy constructor. Objects in the Vectorset should not do any memory management or the behaviour will be undefined. Use with caution.
Note:
The Vectorset will only free memory when the object is destroyed.
See also:
std::vector, std::set
Member Typedef Documentation
template<typename _T> typedef ConstVectorset<_T>::iterator BWAPI::Vectorset< _T >::iterator
The iterator is used to traverse the elements in the set.
It is used the same way as in the stl containers.
Reimplemented from BWAPI::ConstVectorset< _T >.
Constructor & Destructor Documentation
template<typename _T> BWAPI::Vectorset< _T >::Vectorset (size_t initialSize = 16) [inline]
This is the default constructor.
The Vectorset will allocate memory for the given number of elements (or 16 by default).
Parameters:
initialSize The number of elements of type _T to allocate memory for.
template<typename _T> BWAPI::Vectorset< _T >::Vectorset (const Vectorset< _T > & other) [inline]
This is the copy constructor.
The Vectorset will allocate only the necessary space to copy the other Vectorset's contents.
Parameters:
other Reference to the Vectorset of the same type whose contents will be copied.
Note:
Duplicate entries are not removed.
template<typename _T> BWAPI::Vectorset< _T >::Vectorset (const ConstVectorset< _T > & other) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
template<typename _T> BWAPI::Vectorset< _T >::Vectorset (Vectorset< _T > && other) [inline]
This is the move constructor.
The Vectorset will steal the data pointer from the other Vectorset.
Parameters:
other Reference to the Vectorset of the same type whose contents will be moved.
Note:
Duplicate entries are not removed.
template<typename _T> BWAPI::Vectorset< _T >::Vectorset (const _T * pArray, size_t arrSize) [inline]
This constructor uses an existing array of objects and copies them into the vector.
The Vectorset will allocate only enough memory to copy the array's contents.
Parameters:
pArray Pointer to an array of objects of type _T.
arrSize The number of elements contained in the given array.
Note:
Duplicate entries are not removed.
Member Function Documentation
template<typename _T> Vectorset<_T>& BWAPI::Vectorset< _T >::operator= (const Vectorset< _T > & other) [inline]
This is the copy assignment operator.
The contents of the current container are erased and replaced with the contents of other.
Returns:
A reference to the current object.
template<typename _T> Vectorset<_T>& BWAPI::Vectorset< _T >::operator= (const ConstVectorset< _T > & other) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
template<typename _T> Vectorset& BWAPI::Vectorset< _T >::operator= (Vectorset< _T > && other) [inline]
This is the move assignment operator.
The contents of the current container are discarded, and the contents of other moved into this.
Returns:
A reference to the current object.
template<typename _T> Vectorset& BWAPI::Vectorset< _T >::operator+= (const ConstVectorset< _T > & other) [inline]
Pushes all values of another Vectorset to the back of this one, expanding it to contain exactly the number of elements in both Vectorsets if necessary.
Parameters:
other The other Vectorset of the same type whose values will be appended to this one.
Note:
Duplicate entries are not removed.
Returns:
A reference to the current object.
See also:
operator|=
template<typename _T> Vectorset& BWAPI::Vectorset< _T >::operator|= (const ConstVectorset< _T > & other) [inline]
Inserts all elements of another vector only if each element does not already exsist.
Parameters:
other Another Vectorset of the same type whose elements will be inserted into this one.
Returns:
A reference to the current object.
See also:
operator+=
template<typename _T> size_t BWAPI::Vectorset< _T >::max_size () const [inline]
Retrieves the current capacity of the Vectorset.
Returns:
The number of elements this Vectorset can contain before needing to allocate more memory.
Referenced by BWAPI::Vectorset< BWAPI::Bullet >::expand().
template<typename _T> void BWAPI::Vectorset< _T >::erase (const _T & val) [inline]
Erases all values found in the Vectorset.
When a value is found, it is erased and the function continues searching for the same value until it reaches the end of the Vectorset.
Parameters:
val The value to search for and erase.
Note:
This function does not preserve order. If you wish to preserve order, see remove.
Referenced by BWAPI::Vectorset< BWAPI::Bullet >::erase(), and BWAPI::Vectorset< BWAPI::Bullet >::erase_if().
template<typename _T> iterator BWAPI::Vectorset< _T >::erase (iterator iter) [inline]
Erases the value at an iterator for this Vectorset.
The advantage of this function is that searching for the value is not necessary.
Parameters:
iter A valid iterator for the position to erase. This iterator must be within the scope of the Vectorset or the result will be undefined.
Returns:
iterator to next element.
Note:
This function does not preserve order. If you wish to preserve order, see remove.
template<typename _T> iterator BWAPI::Vectorset< _T >::erase (iterator first, iterator last) [inline]
Erases the values within a range of iterators for this Vectorset.
Parameters:
first A valid iterator for the starting position to erase. This iterator must be within the scope of the Vectorset or the result will be undefined.
last A valid iterator for the ending position to erase. This iterator must come after first and be within the scope of the Vectorset or the result will be undefined.
Note:
This function does not preserve order. If you wish to preserve order, see remove.
template<typename _T> template<typename Func > void BWAPI::Vectorset< _T >::erase_if (const Func & pred) [inline]
Works similar to the STL algorithm remove_if.
Iterates and calls a function predicate for each element in the Vectorset. If the predicate call returns true, then the value is erased by calling erase.
Parameters:
pred Function predicate used to determine if a value is removed.
See also:
std::remove_if, remove_if
template<typename _T> void BWAPI::Vectorset< _T >::remove (const _T & val) [inline]
Removes all values found in the Vectorset.
When a value is found, it is removed and the function continues searching for the same value until it reaches the end of the Vectorset.
Parameters:
val The value to search for and remove.
Note:
This function preserves order. It is recommended to use erase for performance if order is not important.
See also:
erase
template<typename _T> void BWAPI::Vectorset< _T >::remove (const iterator & iter) [inline]
Erases the value at an iterator for this Vectorset.
The advantage of this function is that searching for the value is not necessary.
Parameters:
iter A valid iterator for the position to erase. This iterator must be within the scope of the Vectorset or the result will be undefined.
Note:
This function preserves order. It is recommended to use erase for performance if order is not important.
See also:
erase
template<typename _T> template<typename Func > void BWAPI::Vectorset< _T >::remove_if (const Func & pred) [inline]
Works similar to the STL algorithm remove_if.
Iterates and calls a function predicate for each element in the Vectorset. If the predicate call returns true, then the value is removed.
Parameters:
pred Function predicate used to determine if a value is removed.
See also:
std::remove_if, erase_if
template<typename _T> void BWAPI::Vectorset< _T >::clear () [inline]
Clears the Vectorset, removing all elements.
Used the same way as stl containers.
Note:
Because of the restrictions placed on the Vectorset, this function executes a single instruction regardless of the number of entries.
Referenced by BWAPI::Vectorset< BWAPI::Bullet >::operator=().
template<typename _T> void BWAPI::Vectorset< _T >::insert (const _T & val) [inline]
Inserts a new value into the Vectorset only if it does not already exist.
Parameters:
val The value to insert.
See also:
std::set
Referenced by BWAPI::Vectorset< BWAPI::Bullet >::insert(), and BWAPI::Vectorset< BWAPI::Bullet >::operator|=().
template<typename _T> void BWAPI::Vectorset< _T >::insert (const iterator & val) [inline]
Inserts a new value into the Vectorset only if it does not already exist.
Parameters:
val The value to insert.
See also:
std::set
template<typename _T> void BWAPI::Vectorset< _T >::insert (const ConstVectorset< _T > & other) [inline]
Inserts all elements of another vector only if each element does not already exsist.
Parameters:
other Another Vectorset of the same type whose elements will be inserted into this one.
template<typename _T> void BWAPI::Vectorset< _T >::push_back (const _T val) [inline]
Pushes a value to the back of the Vectorset, expanding it if necessary.
Parameters:
val The value to add to the back of this Vectorset.
Note:
Duplicate entries are not removed.
See also:
push_front
Referenced by BWAPI::Vectorset< BWAPI::Bullet >::insert(), BWAPI::ConstVectorset< BWAPI::Bullet >::operator+(), BWAPI::Vectorset< BWAPI::Bullet >::operator+=(), BWAPI::Vectorset< BWAPI::Bullet >::operator=(), BWAPI::ConstVectorset< BWAPI::Bullet >::operator|(), and BWAPI::Vectorset< BWAPI::Bullet >::push_back().
template<typename _T> void BWAPI::Vectorset< _T >::push_back (const iterator & val) [inline]
Pushes a value to the back of the Vectorset, expanding it if necessary.
Parameters:
val The value to add to the back of this Vectorset.
Note:
Duplicate entries are not removed.
See also:
push_front
template<typename _T> void BWAPI::Vectorset< _T >::push_back (const ConstVectorset< _T > & other) [inline]
Pushes all values of another Vectorset to the back of this one, expanding it to contain exactly the number of elements in both Vectorsets if necessary.
Parameters:
other The other Vectorset of the same type whose values will be appended to this one.
Note:
Duplicate entries are not removed.
template<typename _T> void BWAPI::Vectorset< _T >::push_front (const _T val) [inline]
Pushes a value to the front of the Vectorset, expanding it if necessary.
Parameters:
val The value to add to the back of this Vectorset.
Note:
Duplicate entries are not removed.
For efficiency, it is recommended to use push_back.
See also:
push_back
Referenced by BWAPI::Vectorset< BWAPI::Bullet >::push_front().
template<typename _T> void BWAPI::Vectorset< _T >::push_front (const iterator & val) [inline]
Pushes a value to the front of the Vectorset, expanding it if necessary.
Parameters:
val The value to add to the back of this Vectorset.
Note:
Duplicate entries are not removed.
For efficiency, it is recommended to use push_back.
See also:
push_back
template<typename _T> void BWAPI::Vectorset< _T >::pop_back () [inline]
Todo:
change return value to copy of value that was popped
See also:
pop_front
template<typename _T> void BWAPI::Vectorset< _T >::pop_front () [inline]
Todo:
change return value to copy of value that was popped
Note:
For efficiency, it is recommended to use pop_back.
See also:
pop_back
template<typename _T> bool BWAPI::Vectorset< _T >::expand (size_t additionalElements = 1) [inline, protected]
Expands the container if it currently does not have the capacity for the number of additional elements.
Return values:
true If space is available.
false If realloc failed.
Referenced by BWAPI::Vectorset< BWAPI::Bullet >::push_back(), and BWAPI::Vectorset< BWAPI::Bullet >::push_front().
The documentation for this class was generated from the following file:
Vectorset.h