BWAPI: BWAPI::ConstVectorset< T > Class Template Reference
BWAPI::ConstVectorset< T > Class Template Reference
The Vectorset is a class template designed specifically for trivial classes or PODs and performance.
Public Types
typedef BWAPI::VSetIterator< T > iterator
The iterator is used to traverse the elements in the set.
typedef std::reverse_iterator
< iterator > reverse_iterator
Public Member Functions
ConstVectorset (const void *pArray, size_t arrSize=0)
This constructor uses an existing array of objects and copies them into the vector.
ConstVectorset (const ConstVectorset &other)
T back () const
iterator begin () const
bool empty () const
Checks if the Vectorset is empty.
iterator end () const
bool exists (const T &element) const
This function checks if an element exists in the Vectorset.
iterator find (const T &value) const
T front () const
template<typename _V , typename _C >
T getBest (const _V &cmpValue, const _C &cmpProc) const
Iterates the Vectorset and retrieves the best entry using two callback procedures.
template<typename _V >
T least (const _V &cmpValue) const
Iterates the Vectorset and retrieves the best entry using two callback procedures.
template<typename _V >
T most (const _V &cmpValue) const
Iterates the Vectorset and retrieves the best entry using two callback procedures.
operator bool () const
Used as a macro to check if the Vectorset is empty.
operator void * () const
Retrieves a pointer to the raw data in the Vectorset.
Vectorset< T > operator+ (const ConstVectorset< T > &other) const
Creates a new Vectorset containing all elements of the current Vectorset with all elements of the other Vectorset appended on to it.
Vectorset< T > operator+ (const T &val) const
bool operator== (const ConstVectorset< T > &other) const
Compares this Vectorset with another Vectorset of the same type.
T operator[] (unsigned int index) const
Array indexing operator.
Vectorset< T > operator| (const ConstVectorset< T > &other) const
Creates a new Vectorset containing all elements of the current Vectorset and all elements of the other Vectorset with duplicates removed.
Vectorset< T > operator| (const T &val) const
T rand () const
This macro is used to choose a random value from a Vectorset.
reverse_iterator rbegin () const
reverse_iterator rend () const
size_t size () const
Retrieves the number of elements currently in the Vectorset.
template<typename _V >
int total (const _V &valProc) const
Calculates a total by applying a functor to each element and adding what the functor returns.
Protected Attributes
T * pEndArr
T * pStartArr
Detailed Description
template<typename T>
class BWAPI::ConstVectorset< T >
The Vectorset is a class template designed specifically for trivial classes or PODs and performance.
It mimics the usage of various stl containers (specifically the Vector and Set) in order to replace them. The Vectorset is designed for BWAPI usage and is recommended, especially if stl containers are causing a bottleneck in your bot's code.
Warning
The Vectorset should only be used with objects that have a trivial destructor and trivial copy constructor. Objects in the Vectorset should not do any memory management or the behaviour will be undefined. Use with caution.
Note
The Vectorset will only free memory when the object is destroyed.
See also
std::vector, std::set
Member Typedef Documentation
template<typename T> typedef BWAPI::VSetIterator<T> BWAPI::ConstVectorset< T >::iterator
The iterator is used to traverse the elements in the set.
It is used the same way as in the stl containers.
template<typename T> typedef std::reverse_iterator<iterator> BWAPI::ConstVectorset< T >::reverse_iterator
Constructor & Destructor Documentation
template<typename T> BWAPI::ConstVectorset< T >::ConstVectorset (const void * pArray, size_t arrSize = 0)
This constructor uses an existing array of objects and copies them into the vector.
The Vectorset will allocate only enough memory to copy the array's contents.
Parameters
pArray Pointer to an array of objects of type T.
arrSize The number of elements contained in the given array.
Note
Duplicate entries are not removed.
template<typename T> BWAPI::ConstVectorset< T >::ConstVectorset (const ConstVectorset< T > & other)
Member Function Documentation
template<typename T> Vectorset<T> BWAPI::ConstVectorset< T >::operator+ (const ConstVectorset< T > & other) const
Creates a new Vectorset containing all elements of the current Vectorset with all elements of the other Vectorset appended on to it.
Parameters
other The other Vectorset of the same type to use in combination.
Returns
A new Vectorset containing the contents of both this and other.
Note
Duplicate entries are not removed.
See also
operator|
template<typename T> Vectorset<T> BWAPI::ConstVectorset< T >::operator+ (const T & val) const
template<typename T> Vectorset<T> BWAPI::ConstVectorset< T >::operator| (const ConstVectorset< T > & other) const
Creates a new Vectorset containing all elements of the current Vectorset and all elements of the other Vectorset with duplicates removed.
Parameters
other The other Vectorset of the same type to use in combination.
Returns
A new Vectorset containing the contents of both this and other.
template<typename T> Vectorset<T> BWAPI::ConstVectorset< T >::operator| (const T & val) const
template<typename T> bool BWAPI::ConstVectorset< T >::operator== (const ConstVectorset< T > & other) const
Compares this Vectorset with another Vectorset of the same type.
Parameters
other A Vectorset of the same type to use for comparison.
Return values
true if the other Vectorset is exactly the same as this one.
false if at least one element in this Vectorset is not found in the other, or if they are not in the exact same positions.
Note
This simply calls memcmp.
template<typename T> BWAPI::ConstVectorset< T >::operator void * () const
Retrieves a pointer to the raw data in the Vectorset.
Note
Vectorset data is simply an array.
Returns
A pointer to the Vectorset's array data.
template<typename T> BWAPI::ConstVectorset< T >::operator bool () const
Used as a macro to check if the Vectorset is empty.
Return values
true if the Vectorset is not empty.
false if the Vectorset is empty.
template<typename T> T BWAPI::ConstVectorset< T >::operator[] (unsigned int index) const
Array indexing operator.
Todo:
Needs to be modified
Parameters
index The array index in the Vectorset to retrieve the value from.
template<typename T> bool BWAPI::ConstVectorset< T >::exists (const T & element) const
This function checks if an element exists in the Vectorset.
Parameters
element The value to search for in the Vectorset.
Return values
true if the element is in the Vectorset.
false if the element was not found.
template<typename T> T BWAPI::ConstVectorset< T >::rand () const
This macro is used to choose a random value from a Vectorset.
It returns a default T value if the Vectorset is empty.
Todo:
needs to be modified
Note
This function calls the rand() function. A call to srand() should be used for initialization.
See also
rand()
Referenced by BWAPI::ConstVectorset< _T >::rand().
template<typename T> template<typename _V , typename _C > T BWAPI::ConstVectorset< T >::getBest (const _V & cmpValue, const _C & cmpProc) const
Iterates the Vectorset and retrieves the best entry using two callback procedures.
The first returning the value to compare, the second being a binary comparison.
Parameters
cmpValue A functor taking one argument, T, and returning a value to compare.
cmpProc A functor taking two values, (the ones returned by cmpValue), and returns a boolean indicating that the first value passed in is the new best value.
Return values
NULL If the Vectorset is empty.
Returns
A T representing the best in the Vectorset.
Referenced by BWAPI::ConstVectorset< _T >::least(), and BWAPI::ConstVectorset< _T >::most().
template<typename T> template<typename _V > T BWAPI::ConstVectorset< T >::most (const _V & cmpValue) const
Iterates the Vectorset and retrieves the best entry using two callback procedures.
The first returning the value to compare, the second being a binary comparison.
Parameters
cmpValue A functor taking one argument, T, and returning a value to compare.
cmpProc A functor taking two values, (the ones returned by cmpValue), and returns a boolean indicating that the first value passed in is the new best value.
Return values
NULL If the Vectorset is empty.
Returns
A T representing the best in the Vectorset.
See also
getBest
template<typename T> template<typename _V > T BWAPI::ConstVectorset< T >::least (const _V & cmpValue) const
Iterates the Vectorset and retrieves the best entry using two callback procedures.
The first returning the value to compare, the second being a binary comparison.
Parameters
cmpValue A functor taking one argument, T, and returning a value to compare.
cmpProc A functor taking two values, (the ones returned by cmpValue), and returns a boolean indicating that the first value passed in is the new best value.
Return values
NULL If the Vectorset is empty.
Returns
A T representing the best in the Vectorset.
See also
getBest
template<typename T> template<typename _V > int BWAPI::ConstVectorset< T >::total (const _V & valProc) const
Calculates a total by applying a functor to each element and adding what the functor returns.
Parameters
valProc A unary functor that takes T as a parameter and returns the integer used to add to the total.
Returns
An integer representing the sum of results from valProc applied to every element in the Vectorset.
template<typename T> size_t BWAPI::ConstVectorset< T >::size () const
Retrieves the number of elements currently in the Vectorset.
Returns
The number of elements contained in this Vectorset.
Note
For efficiency it is recommended to use empty() to check if the Vectorset has 0 elements.
See also
empty
Referenced by BWAPI::ConstVectorset< _T >::operator+(), BWAPI::ConstVectorset< _T >::operator==(), BWAPI::ConstVectorset< _T >::operator[](), BWAPI::ConstVectorset< _T >::operator|(), BWAPI::Vectorset< BWAPI::Bullet >::push_back(), BWAPI::ConstVectorset< _T >::rand(), and BWAPI::Vectorset< BWAPI::Bullet >::Vectorset().
template<typename T> bool BWAPI::ConstVectorset< T >::empty () const
Checks if the Vectorset is empty.
Return values
true if the Vectorset is empty.
false if the Vectorset contains elements.
Referenced by BWAPI::ConstVectorset< _T >::getBest(), BWAPI::ConstVectorset< _T >::operator bool(), and BWAPI::ConstVectorset< _T >::operator==().
template<typename T> iterator BWAPI::ConstVectorset< T >::begin () const
Referenced by BWAPI::ConstVectorset< _T >::find(), BWAPI::ConstVectorset< _T >::front(), BWAPI::ConstVectorset< _T >::getBest(), BWAPI::Vectorset< BWAPI::Bullet >::insert(), and BWAPI::ConstVectorset< _T >::total().
template<typename T> reverse_iterator BWAPI::ConstVectorset< T >::rbegin () const
Referenced by BWAPI::ConstVectorset< _T >::back().
template<typename T> iterator BWAPI::ConstVectorset< T >::end () const
Referenced by BWAPI::ConstVectorset< _T >::exists(), BWAPI::ConstVectorset< _T >::find(), BWAPI::ConstVectorset< _T >::getBest(), BWAPI::Vectorset< BWAPI::Bullet >::insert(), and BWAPI::ConstVectorset< _T >::total().
template<typename T> reverse_iterator BWAPI::ConstVectorset< T >::rend () const
template<typename T> T BWAPI::ConstVectorset< T >::front () const
Referenced by BWAPI::ConstVectorset< _T >::getBest().
template<typename T> T BWAPI::ConstVectorset< T >::back () const
template<typename T> iterator BWAPI::ConstVectorset< T >::find (const T & value) const
Referenced by BWAPI::ConstVectorset< _T >::exists().
Member Data Documentation
template<typename T> T* BWAPI::ConstVectorset< T >::pStartArr protected
Referenced by BWAPI::ConstVectorset< _T >::begin(), BWAPI::ConstVectorset< _T >::empty(), BWAPI::ConstVectorset< _T >::operator void *(), BWAPI::ConstVectorset< _T >::operator==(), BWAPI::ConstVectorset< _T >::operator[](), BWAPI::ConstVectorset< _T >::rand(), BWAPI::ConstVectorset< _T >::rend(), and BWAPI::ConstVectorset< _T >::size().
template<typename T> T* BWAPI::ConstVectorset< T >::pEndArr protected
Referenced by BWAPI::ConstVectorset< _T >::empty(), BWAPI::ConstVectorset< _T >::end(), BWAPI::ConstVectorset< _T >::rbegin(), and BWAPI::ConstVectorset< _T >::size().