BWAPI: BWAPI::Type< T, UnknownId > Class Template Reference
BWAPI::Type< T, UnknownId > Class Template Reference
Base superclass for all BWAPI Types.
#include <Type.h>
Public Types
typedef ConstVectorset< T > const_set
The constant set that contains the current type.
typedef Typeset< T > set
The set that contains the current type.
Public Member Functions
Type (int id)
Expected type constructor.
const char * c_str () const
Retrieves the variable name of the type as a c-style string.
int getID () const
Retrieves this type's identifier.
const std::string & getName () const
Retrieves the variable name of the type.
bool isValid () const
Checks if the current type has a valid identifier.
operator int () const
Conversion/convenience operator to convert this type to its primitive type.
const std::string & toString () const
Static Public Member Functions
static T getType (std::string name)
Searches for the type associated with the given string and returns it.
Protected Types
typedef std::unordered_map
< std::string, T > typeMapT
Protected Attributes
int tid
Primitive storage unit for the type identifier (t id)
Static Protected Attributes
static const std::string typeNames [UnknownId+1]
Array of strings containing the type names.
Friends
std::ostream & operator<< (std::ostream &out, const Type< T, UnknownId > &t)
Output stream operator overload.
Detailed Description
template<class T, int UnknownId>
class BWAPI::Type< T, UnknownId >
Base superclass for all BWAPI Types.
Member Typedef Documentation
template<class T, int UnknownId> typedef Typeset<T> BWAPI::Type< T, UnknownId >::set
The set that contains the current type.
template<class T, int UnknownId> typedef ConstVectorset<T> BWAPI::Type< T, UnknownId >::const_set
The constant set that contains the current type.
Constructor & Destructor Documentation
template<class T, int UnknownId> BWAPI::Type< T, UnknownId >::Type (int id) [inline, explicit]
Expected type constructor.
If the type is an invalid type, then it becomes Types::Unknown. A type is invalid if its value is less than 0 or greater than Types::Unknown.
Parameters:
id (optional) The id that corresponds to this type. It is typically an integer value that corresponds to an internal Broodwar type. If the given id is invalid, then it becomes Types::Unknown. If it is omitted, then it becomes Types::None.
Member Function Documentation
template<class T, int UnknownId> BWAPI::Type< T, UnknownId >::operator int () const [inline]
Conversion/convenience operator to convert this type to its primitive type.
template<class T, int UnknownId> int BWAPI::Type< T, UnknownId >::getID () const [inline]
Retrieves this type's identifier.
Returns:
An integer representation of this type.
template<class T, int UnknownId> bool BWAPI::Type< T, UnknownId >::isValid () const [inline]
Checks if the current type has a valid identifier.
The purpose of this function is to prevent buffer overflows if a type has been handled improperly.
A type is valid if it is between 0 and Unknown (inclusive).
Returns:
true If this type is valid and false otherwise.
Referenced by BWAPI::Type< GameType, GameTypes::Enum::Unknown >::getName().
template<class T, int UnknownId> const std::string& BWAPI::Type< T, UnknownId >::getName () const [inline]
Retrieves the variable name of the type.
Returns:
Reference to std::string object containing the name.
Referenced by BWAPI::Type< GameType, GameTypes::Enum::Unknown >::c_str(), and BWAPI::Type< GameType, GameTypes::Enum::Unknown >::toString().
template<class T, int UnknownId> const std::string& BWAPI::Type< T, UnknownId >::toString () const [inline]
Retrieves the variable name of the type.
Returns:
Reference to std::string object containing the name.
template<class T, int UnknownId> const char* BWAPI::Type< T, UnknownId >::c_str () const [inline]
Retrieves the variable name of the type as a c-style string.
Meant to be a convenience member.
Returns:
Pointer to constant c-style string containing the name.
template<class T, int UnknownId> static T BWAPI::Type< T, UnknownId >::getType (std::string name) [inline, static]
Searches for the type associated with the given string and returns it.
Parameters:
name A string containing the name of the type.
Returns:
The type that resolves to the given name.
Friends And Related Function Documentation
template<class T, int UnknownId> std::ostream& operator<< (std::ostream & out, const Type< T, UnknownId > & t) [friend]
Output stream operator overload.
Allows printing of the type without calling Type::getName.
Member Data Documentation
template<class T, int UnknownId> int BWAPI::Type< T, UnknownId >::tid [protected]
Primitive storage unit for the type identifier (t id)
Referenced by BWAPI::Type< GameType, GameTypes::Enum::Unknown >::getID(), BWAPI::Type< GameType, GameTypes::Enum::Unknown >::getName(), BWAPI::Type< GameType, GameTypes::Enum::Unknown >::isValid(), and BWAPI::Type< GameType, GameTypes::Enum::Unknown >::operator int().
template<class T, int UnknownId> const std::string BWAPI::Type< T, UnknownId >::typeNames[UnknownId+1] [static, protected]
Array of strings containing the type names.
Referenced by BWAPI::Type< GameType, GameTypes::Enum::Unknown >::getName().
The documentation for this class was generated from the following file:
Type.h