BWAPI: BWAPI::BroodwarOutputDevice Class Reference
BWAPI::BroodwarOutputDevice Class Reference
Public Member Functions
BroodwarOutputDevice (Text::Enum defaultColor=Text::Yellow)
BroodwarOutputDevice (const BroodwarOutputDevice &o)
std::streamsize write (const char *s, std::streamsize n)
Detailed Description
Output device for writing text to the screen as a notification.
Normally when you write stuff in Starcraft, the text wraps at word boundaries when it would otherwise exceed the screen width. When this happens any Text::Enum color in the message is lost and the next line will be some default color. To fix this color problem this device keeps track of the width of the text in the buffer and manually wraps when needed (not on word boundaries), and then colors the next line with the current color again before continuing to write.
Since
4.2.0
Constructor & Destructor Documentation
BWAPI::BroodwarOutputDevice::BroodwarOutputDevice (Text::Enum defaultColor = Text::Yellow) explicit
References std::stringbuf::sputc().
BWAPI::BroodwarOutputDevice::BroodwarOutputDevice (const BroodwarOutputDevice & o)
Member Function Documentation
std::streamsize BWAPI::BroodwarOutputDevice::write (const char * s, std::streamsize n)
References BWAPI::BroodwarPtr, BWAPI::Text::isColor(), BWAPI::Text::Previous, BWAPI::Game::printf(), std::stringbuf::sputc(), and std::stringbuf::str().