var namespaces =
[
    [ "BWAPI::BulletTypes", "namespace_b_w_a_p_i_1_1_bullet_types.html", "namespace_b_w_a_p_i_1_1_bullet_types" ],
    [ "BWAPI::BulletTypes::Enum", "namespace_b_w_a_p_i_1_1_bullet_types_1_1_enum.html", "namespace_b_w_a_p_i_1_1_bullet_types_1_1_enum" ],
    [ "BWAPI::Colors", "namespace_b_w_a_p_i_1_1_colors.html", "namespace_b_w_a_p_i_1_1_colors" ],
    [ "BWAPI::DamageTypes", "namespace_b_w_a_p_i_1_1_damage_types.html", "namespace_b_w_a_p_i_1_1_damage_types" ],
    [ "BWAPI::DamageTypes::Enum", "namespace_b_w_a_p_i_1_1_damage_types_1_1_enum.html", "namespace_b_w_a_p_i_1_1_damage_types_1_1_enum" ],
    [ "BWAPI::Errors", "namespace_b_w_a_p_i_1_1_errors.html", "namespace_b_w_a_p_i_1_1_errors" ],
    [ "BWAPI::Errors::Enum", "namespace_b_w_a_p_i_1_1_errors_1_1_enum.html", "namespace_b_w_a_p_i_1_1_errors_1_1_enum" ],
    [ "BWAPI::ExplosionTypes", "namespace_b_w_a_p_i_1_1_explosion_types.html", "namespace_b_w_a_p_i_1_1_explosion_types" ],
    [ "BWAPI::ExplosionTypes::Enum", "namespace_b_w_a_p_i_1_1_explosion_types_1_1_enum.html", "namespace_b_w_a_p_i_1_1_explosion_types_1_1_enum" ],
    [ "BWAPI::GameTypes", "namespace_b_w_a_p_i_1_1_game_types.html", "namespace_b_w_a_p_i_1_1_game_types" ],
    [ "BWAPI::GameTypes::Enum", "namespace_b_w_a_p_i_1_1_game_types_1_1_enum.html", "namespace_b_w_a_p_i_1_1_game_types_1_1_enum" ],
    [ "BWAPI::Orders", "namespace_b_w_a_p_i_1_1_orders.html", "namespace_b_w_a_p_i_1_1_orders" ],
    [ "BWAPI::Orders::Enum", "namespace_b_w_a_p_i_1_1_orders_1_1_enum.html", "namespace_b_w_a_p_i_1_1_orders_1_1_enum" ],
    [ "BWAPI::PlayerTypes", "namespace_b_w_a_p_i_1_1_player_types.html", "namespace_b_w_a_p_i_1_1_player_types" ],
    [ "BWAPI::PlayerTypes::Enum", "namespace_b_w_a_p_i_1_1_player_types_1_1_enum.html", "namespace_b_w_a_p_i_1_1_player_types_1_1_enum" ],
    [ "BWAPI::Races", "namespace_b_w_a_p_i_1_1_races.html", "namespace_b_w_a_p_i_1_1_races" ],
    [ "BWAPI::Races::Enum", "namespace_b_w_a_p_i_1_1_races_1_1_enum.html", "namespace_b_w_a_p_i_1_1_races_1_1_enum" ],
    [ "BWAPI::TechTypes", "namespace_b_w_a_p_i_1_1_tech_types.html", "namespace_b_w_a_p_i_1_1_tech_types" ],
    [ "BWAPI::TechTypes::Enum", "namespace_b_w_a_p_i_1_1_tech_types_1_1_enum.html", "namespace_b_w_a_p_i_1_1_tech_types_1_1_enum" ],
    [ "BWAPI::Text", "namespace_b_w_a_p_i_1_1_text.html", "namespace_b_w_a_p_i_1_1_text" ],
    [ "BWAPI::Text::Size", "namespace_b_w_a_p_i_1_1_text_1_1_size.html", "namespace_b_w_a_p_i_1_1_text_1_1_size" ],
    [ "BWAPI::UnitCommandTypes", "namespace_b_w_a_p_i_1_1_unit_command_types.html", "namespace_b_w_a_p_i_1_1_unit_command_types" ],
    [ "BWAPI::UnitCommandTypes::Enum", "namespace_b_w_a_p_i_1_1_unit_command_types_1_1_enum.html", "namespace_b_w_a_p_i_1_1_unit_command_types_1_1_enum" ],
    [ "BWAPI::UnitSizeTypes", "namespace_b_w_a_p_i_1_1_unit_size_types.html", "namespace_b_w_a_p_i_1_1_unit_size_types" ],
    [ "BWAPI::UnitSizeTypes::Enum", "namespace_b_w_a_p_i_1_1_unit_size_types_1_1_enum.html", "namespace_b_w_a_p_i_1_1_unit_size_types_1_1_enum" ],
    [ "BWAPI::UnitTypes", "namespace_b_w_a_p_i_1_1_unit_types.html", "namespace_b_w_a_p_i_1_1_unit_types" ],
    [ "BWAPI::UnitTypes::Enum", "namespace_b_w_a_p_i_1_1_unit_types_1_1_enum.html", "namespace_b_w_a_p_i_1_1_unit_types_1_1_enum" ],
    [ "BWAPI::UpgradeTypes", "namespace_b_w_a_p_i_1_1_upgrade_types.html", "namespace_b_w_a_p_i_1_1_upgrade_types" ],
    [ "BWAPI::UpgradeTypes::Enum", "namespace_b_w_a_p_i_1_1_upgrade_types_1_1_enum.html", "namespace_b_w_a_p_i_1_1_upgrade_types_1_1_enum" ],
    [ "BWAPI::WeaponTypes", "namespace_b_w_a_p_i_1_1_weapon_types.html", "namespace_b_w_a_p_i_1_1_weapon_types" ],
    [ "BWAPI::WeaponTypes::Enum", "namespace_b_w_a_p_i_1_1_weapon_types_1_1_enum.html", "namespace_b_w_a_p_i_1_1_weapon_types_1_1_enum" ]
];