BWAPI: BWAPI::Type< T, UnknownId > Class Template Reference
BWAPI::Type< T, UnknownId > Class Template Reference
Base superclass for all BWAPI Types.
Public Types
typedef std::deque< T > list
A list type that contains the current type.
typedef SetContainer< T > set
A set type that contains the current type.
Public Member Functions
Type (int id)
Expected type constructor.
const char * c_str () const
Retrieves the variable name of the type as a c-style string.
int getID () const
Retrieves this type's identifier.
const std::string & getName () const
Retrieves the variable name of the type.
bool isValid () const
Checks if the current type has a valid identifier.
operator int () const
Conversion/convenience operator to convert this type to its primitive type.
const std::string & toString () const
Retrieves the variable name of the type.
Static Public Member Functions
static T getType (std::string name)
Searches for the type associated with the given string and returns it.
Protected Types
typedef std::unordered_map
< std::string, T > typeMapT
Type that maps names to their type values.
Protected Attributes
int tid
Primitive storage unit for the type identifier (t id)
Static Protected Attributes
static const std::string typeNames [UnknownId+1]
Array of strings containing the type names.
Friends
std::ostream & operator<< (std::ostream &out, const Type< T, UnknownId > &t)
Output stream operator overload.
std::wostream & operator<< (std::wostream &out, const Type< T, UnknownId > &t)
Detailed Description
template<class T, int UnknownId>
class BWAPI::Type< T, UnknownId >
Base superclass for all BWAPI Types.
Member Typedef Documentation
template<class T, int UnknownId> typedef std::unordered_map<std::string,T> BWAPI::Type< T, UnknownId >::typeMapT protected
Type that maps names to their type values.
template<class T, int UnknownId> typedef SetContainer<T> BWAPI::Type< T, UnknownId >::set
A set type that contains the current type.
template<class T, int UnknownId> typedef std::deque<T> BWAPI::Type< T, UnknownId >::list
A list type that contains the current type.
Constructor & Destructor Documentation
template<class T, int UnknownId> BWAPI::Type< T, UnknownId >::Type (int id) explicit
Expected type constructor.
If the type is an invalid type, then it becomes Types::Unknown. A type is invalid if its value is less than 0 or greater than Types::Unknown.
Parameters
id (optional) The id that corresponds to this type. It is typically an integer value that corresponds to an internal Broodwar type. If the given id is invalid, then it becomes Types::Unknown. If it is omitted, then it becomes Types::None.
Member Function Documentation
template<class T, int UnknownId> BWAPI::Type< T, UnknownId >::operator int () const
Conversion/convenience operator to convert this type to its primitive type.
References BWAPI::Type< T, UnknownId >::tid.
template<class T, int UnknownId> int BWAPI::Type< T, UnknownId >::getID () const
Retrieves this type's identifier.
Returns
An integer representation of this type.
References BWAPI::Type< T, UnknownId >::tid.
template<class T, int UnknownId> bool BWAPI::Type< T, UnknownId >::isValid () const
Checks if the current type has a valid identifier.
The purpose of this function is to prevent buffer overflows if a type has been handled improperly.
A type is valid if it is between 0 and Unknown (inclusive).
Returns
true If this type is valid and false otherwise.
Referenced by BWAPI::Type< T, UnknownId >::getName().
template<class T, int UnknownId> const std::string& BWAPI::Type< T, UnknownId >::getName () const
Retrieves the variable name of the type.
Returns
Reference to std::string object containing the name.
References BWAPI::Type< T, UnknownId >::isValid().
Referenced by BWAPI::Type< T, UnknownId >::c_str(), and BWAPI::Type< T, UnknownId >::toString().
template<class T, int UnknownId> const std::string& BWAPI::Type< T, UnknownId >::toString () const
Retrieves the variable name of the type.
Returns
Reference to std::string object containing the name.
References BWAPI::Type< T, UnknownId >::getName().
template<class T, int UnknownId> const char* BWAPI::Type< T, UnknownId >::c_str () const
Retrieves the variable name of the type as a c-style string.
Meant to be a convenience member.
Returns
Pointer to constant c-style string containing the name.
References std::string::c_str(), and BWAPI::Type< T, UnknownId >::getName().
template<class T, int UnknownId> static T BWAPI::Type< T, UnknownId >::getType (std::string name) static
Searches for the type associated with the given string and returns it.
Parameters
name A string containing the name of the type.
Returns
The type that resolves to the given name.
References std::string::begin(), std::string::end(), std::unordered_map< K, T >::end(), std::string::erase(), std::unordered_map< K, T >::find(), std::remove_if(), and std::transform().
Friends And Related Function Documentation
template<class T, int UnknownId> std::ostream& operator<< (std::ostream & out, const Type< T, UnknownId > & t) friend
Output stream operator overload.
Allows printing of the type without calling Type::getName.
template<class T, int UnknownId> std::wostream& operator<< (std::wostream & out, const Type< T, UnknownId > & t) friend
Member Data Documentation
template<class T, int UnknownId> int BWAPI::Type< T, UnknownId >::tid protected
Primitive storage unit for the type identifier (t id)
Referenced by BWAPI::Type< T, UnknownId >::getID(), and BWAPI::Type< T, UnknownId >::operator int().
template<class T, int UnknownId> const std::string BWAPI::Type< T, UnknownId >::typeNames[UnknownId+1] static protected
Array of strings containing the type names.